language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - antiword
    - language-pack-he
install:
- ".travis/install.sh"
script:
- ".travis/script.sh"
after_success:
- ".travis/after_success.sh"
env:
  global:
  - secure: PTlfkTVXqmranGY4ibdJuVqxCHyreI26HacoTPI8iH92uuoNxvo1k6fgf83mIeU+BggsYtWu5ysQE9Eu4VTkuE8ThTug0LLP0nxAQqy7EfZeYrLyZ5IS2KMpijRpIF/kEexcFxEBYiRUde7Bn6JzrBt+FJktWf1wAxRYISiamEBqWLt20rrOpdrfPSOCbvY26uoZC8XJntT4s0dJB5+UOJnV9psA29AXloNasg7uj0YFbCDJ7TmwKqYqM8qrXfNmp3a70lHtmpcZWbnjFPBiq3u1azO+Ipej4L1dFdC5iE4mLFrhzsf0T8UfWXVj/lWW3BnucdLBOsZpLOmhajKF9nc5KBj9so9yKodzVxQG1hODJxzITteP/P+ZNt8PcQyKkNS3nXQqPZt9MCjELWzlINJF1OmucJDZlCuwdKOlHummA2D3cr3QFI7aUDBQUtDg2tfusBlS6SjgtlDIi7XciA8bVcGQlqcpNZlF7FsGxa2ydywigXgzIiKRTdZ8IzSSpMoG6RuakVW4SWSLQIsjruSSHRdlrcsx+fo0aywmbV/vTFLiiaRrI2zURvY8p4l+QnNX5jPJ0pi2oD+WqXdwIjBvcTibUMksMD0WLfUhFNhBG5edF2TTJE/TL3TIABj9NmS+RJoHCYtoUttAGyyQ2Qo+CVoyPz4Qndh/TT/D5kA=
  - secure: XxjNFb7aqREgyvAe9B3pxze+EA9TsGJA7EZPWlprRFvHXgspuuHEse2p6yLHtdrZqNVA6nndoQxf4HAY0GCR48spPgtbsmg/KiR9+WVxR03R7JcpZlVRZWpKJSRgx4nYPwOZW8EnU8NDhBSrrJifCeCM5YDsmMGqykltzAGE5w9tMtrLeCDG5pxR5NqE+Ox9ABDylo+edVa1qBHzEF7qDy73iO05MBNiF60mZSnXFxZjCIhjdm7MUIe56+JG4NPnsVksiAjIEe9devMTfnKSqwR2KpYMvOBWLweJr1Po/WZyOvHSeVhACqK+KnpjLI6HcqWVEcaEmEtv3U5H35zKYfsDNTlCeZVlpvPbbq0NhmXbfQI7dtMxTQblzZLDpavW5vv/RR83yfGx5hztvX8UMiInlBknTGReBgxH7ZnEE68hvVvKy4JUzrBaxK6uV2YsvC4bPzqEYRe/BMq6qhhqG+rgwJfsu23+o9QZ+HwAHiGdx/crk+Q0dVGZB0tePljkS7pa0HRsgY7329EtrR5qj9PG+RPj5Ie1Y4xYLJxHObxA3Fv5CHGdjUWDQsSU0gdXBSrxRemJXDeqnpq0JS/JSa4S9e8WWQ9rgNeYIgq9VUqnAoV+TZ1HI8qpApzA2viQrREgDFGANZhUS+uDd9H2re5KkU97QHu2uUHIPhlgRNI=
