language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - antiword
    - language-pack-he
install:
- ".travis/install.sh"
script:
- ".travis/script.sh"
after_success:
- ".travis/after_success.sh"
env:
  global:
  - secure: "j2YdrXsDmTMgVqU6qyLH95KD3CZ1F6Tz/W3hV2rR52Haxm+7c3x3LG+mBaRntaBzTbSDfi01HsdFl2MkjqkG1D0uSRoBfT9YIufURYHC77z+F2DReO0Qfb6vE3lILo7rEaBfl5zAAChLEGmQpB1wHkKvScsofr9qb89OwMu9Lq+KypI5PR+1PURQK5MgUoPom8xjkV6h6LMovo6f9uMK2YikA72gEFpCt+A8NEI1Ikb7s4IZoIj9qEdMxSlUG7tUAeFujpRuBz1gzDLMG98oPjw+wE93z9de7TUlJ7VG8mw09Tjnzu8cLrqNDOBWVByJHdgrPcGs52WYpUsgZ6a58geNOBS79B419YNjoDRQp4+EIK/ydbTS9+WnXbl8+om5x4MHhvcKHx5XNxAgTqr9itjhbV4PTlPwdoYrPf+lKudEUtvJHQ9hrQTuyr1O8ssrhH6XDu+kcor13siAhc9I4butmNGZ3bEOA30Svcbf+spsLmmA2IZbeWsqTshYt5SYirZFjlxlydaelOns/dKe/Yb9hNlIMbLY7aPTItLFUUDqIH3ajQvsI4suBMiCRZd84Wmmtn3SoEeL4hgJzjsYNuEreLBCTO2tQdFoTNr6UXBCwIJxgH7v5CeJ3uqKncXVDWkF0tErZ/3R9E6A5kGcRfUU9WMxm5V4eqfrutErM18="
